language: python
dist: xenial
sudo : false
addons:
  apt:
    packages:
    - poppler-utils
python:
  - "2.7"
  - "3.5"
notifications:
  email: false
before_install:
  - pip install pip --upgrade
  - pip install bibtexparser
  - pip install six
  - pip install crossrefapi
  - pip install rapidfuzz
  - pip install unidecode
  - pip install scholarly
# test coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
install:
  - python setup.py install

script: py.test -xv --cov papers.bib tests
#script: tox -e py27 -e py34

after-success: coveralls